### ISSUE TITLE
Components: Standard Conditional Component

### ISSUE THREAD

**Issue by giorgiomarzianidepaolis-was** [meya-ai/community#30]
It could be very useful to have a conditional component like the switch/case instruction.

It could me called meya.conditional and it could be very similar to meya.conditional_nlp_intent but based on a custom variable instead of flow.intent.

This could be an example of use

``` yaml
component: meya.conditional
properties:
    scope: flow
    key: mycustomvar
transitions:
    first_value: first_value_state
    second_value: second_value_state
    third_value: third_value_state
```

**Comment by giorgiomarzianidepaolis-was** [comment]
Here's a workaround I'm using today.

Create a component `SwitchCase`:
```yaml
from meya import Component

class SwitchCase(Component):

    def start(self):
        nextaction = self.properties.get('nextaction')
        return self.respond(message=None, action=nextaction)
```
and here's the state in my flow
```yaml
exists_state:
    component: SwitchCase
    properties:
        nextaction: "{{ flow.myvar }}"
    transitions:
        first_value: first_value
        second_value: second_value
        third_value: third_value
```
